In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([False, False, True, True, True])

In [3]:
a[b]

array([3, 4, 5])

In [4]:
c = a>2
c

array([False, False,  True,  True,  True])

In [5]:
a[c]

array([3, 4, 5])

In [6]:
a[a>2]

array([3, 4, 5])

In [7]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])


In [8]:
# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])


In [9]:
'''
Write a function that takes in time_spent and days_to_cancel and returns mean time spent for 
students who stay at least 7 days
'''

'\nWrite a function that takes in time_spent and days_to_cancel and returns mean time spent for \nstudents who stay at least 7 days\n'