In [1]:
import numpy as np

In [2]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

In [3]:
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [4]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [5]:
'''
Fill in this function. First, for each subway station, calculate the
mean ridership per day. Then, out of all the subway stations, return the
maximum and minimum of these values. That is, find the maximum
mean-ridership-per-day and the minimum mean-ridership-per-day for any
subway station.
'''

def min_and_max_riders_per_day(ridership):
    


SyntaxError: unexpected EOF while parsing (<ipython-input-5-4d0af04b3479>, line 10)

In [20]:
print(ridership.mean(axis=1))
print(ridership.mean(axis=1).max())
print(ridership.mean(axis=1).min())
print(ridership.sum(axis=1))

[1.4000e+00 2.7792e+03 3.7688e+03 3.2356e+03 3.5048e+03 3.4164e+03
 2.5520e+02 6.0000e+00 3.0402e+03 3.4184e+03]
3768.8
1.4
[    7 13896 18844 16178 17524 17082  1276    30 15201 17092]
